name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-rails-4:
    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    uses: ./.github/workflows/ci-common.yml
    with:
      rails: ${{ matrix.rails }}
      ruby: ${{ matrix.ruby }}
      bundler: '1'
    strategy:
      matrix:
        rails: [ '4.0', '4.1', '4.2' ]
        ruby: [ '2.1', '2.2', '2.3', '2.4', '2.5' ]

  test-rails-5:
    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    uses: ./.github/workflows/ci-common.yml
    with:
      rails: ${{ matrix.rails }}
      ruby: ${{ matrix.ruby }}
    strategy:
      matrix:
        rails: [ '5.0.0', '5.1.0', '5.2.0' ]
        ruby: [ '2.4', '2.5', '2.6', '2.7' ]

  test-rails-6:
    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    uses: ./.github/workflows/ci-common.yml
    with:
      rails: ${{ matrix.rails }}
      ruby: ${{ matrix.ruby }}
    strategy:
      matrix:
        rails: [ '6.0.0', '6.1.0' ]
        ruby: [ '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4' ]

  test-rails-7:
    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    uses: ./.github/workflows/ci-common.yml
    with:
      rails: ${{ matrix.rails }}
      ruby: ${{ matrix.ruby }}
    strategy:
      matrix:
        rails: [ '7.0.1', '7.1.0', '7.2.0' ]
        ruby: [ '2.7', '3.0', '3.1', '3.2', '3.3', '3.4' ]
        exclude:
          - { rails: '7.2.0', ruby: '2.7' }
          - { rails: '7.2.0', ruby: '3.0' }

  test-rails-8:
    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    uses: ./.github/workflows/ci-common.yml
    with:
      rails: ${{ matrix.rails }}
      ruby: ${{ matrix.ruby }}
    strategy:
      matrix:
        rails: [ '8.0.0' ]
        ruby: [ '3.2', '3.3', '3.4' ]
